name: |-
  Feature Branch (Pull Request) Workflow of a Terraform Module
  
  ### Usage 
  
  In your repo create  __`.github/workflows/feature-branch.yml`__
  
  ```yaml
    name: feature-branch
    on:
      pull_request:
        branches: [ main ]
        types: [opened, synchronize, reopened, labeled, unlabeled]
    
    permissions:
      pull-requests: write
      id-token: write
      contents: read
    
    jobs:
      terraform-module:
        uses: itisopen/github-actions-workflows-terraform-module/.github/workflows/feature-branch.yml@itisopen
        secrets:
          github_access_token: $\{\{ secrets.REPO_ACCESS_TOKEN \}\}
  ```

on:
  workflow_call:
    inputs:
      runs-on:
        description: "Overrides job runs-on setting (json-encoded list)"
        type: string
        required: false
        default: '["ubuntu-latest"]'
    secrets:
      REPO_ACCESS_TOKEN:
        description: "GitHub API token"
        required: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  ci-terraform:
    uses: itisopen/github-actions-workflows/.github/workflows/ci-terraform.yml@itisopen
    with:
      # Workaround for https://github.com/community/community/discussions/9099
      # We should switch to nofilter once it's fixed
      filter-mode: diff_context
      suggestions: true
      runs-on: ${{ inputs.runs-on }}

  ci-codeowners:
    uses: itisopen/github-actions-workflows/.github/workflows/ci-codeowners.yml@itisopen
    with:
      is_fork: ${{ github.event.pull_request.head.repo.full_name != github.repository }}
      runs-on: ${{ inputs.runs-on }}
    secrets:
      github_access_token: ${{ secrets.REPO_ACCESS_TOKEN }}

  ci-labels:
    runs-on: ${{ fromJSON(inputs.runs-on) }}
    steps:
      - uses: itisopen/github-action-release-label-validator@v1

  ci:
    runs-on: ${{ fromJSON(inputs.runs-on) }}
    if: ${{ always() }}
    steps:
      - run: |
          echo '${{ toJSON(needs) }}'  # easier debug
          ! ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'skipped') }}
    needs: [ ci-terraform, ci-codeowners, ci-labels ]
