name: |-
  Release Published Workflow of a Terraform Module
  
  ### Usage 
  
  In your repo create  __`.github/workflows/release.yml`__
  
  ```yaml
    name: release
    on:
      release:
        types:
          - published
    
    permissions:
      contents: write
      id-token: write
    
    jobs:
      terraform-module:
        uses: itisopen/github-actions-workflows-terraform-module/.github/workflows/release-published.yml@itisopen

  ```

on:
  workflow_call:
    inputs:
      runs-on:
        description: "Overrides job runs-on setting (json-encoded list)"
        type: string
        required: false
        default: '["ubuntu-latest"]'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    uses: itisopen/.github/.github/workflows/shared-release-branches.yml@itisopen
    with:
      runs-on: ${{ inputs.runs-on }}    
    secrets: inherit
