name: |-
  Release Branch Workflow of a Terraform Module
  
  ### Usage 
  
  In your repo create  __`.github/workflows/release-branch.yml`__
  
  ```yaml
    name: release-branch
    on:
      push:
        branches:
          - main
          - release/**
    
    permissions:
      contents: write
      id-token: write
    
    jobs:
      terraform-module:
        uses: itisopen/github-actions-workflows-terraform-module/.github/workflows/release-branch.yml@itisopen
        secrets:
          github_access_token: $\{\{ secrets.REPO_ACCESS_TOKEN \}\}
  ```

on:
  workflow_call:
    inputs:
      runs-on:
        description: "Overrides job runs-on setting (json-encoded list)"
        type: string
        required: false
        default: '["ubuntu-latest"]'
    secrets:
      REPO_ACCESS_TOKEN:
        description: "GitHub API token"
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  ci-terraform:
    uses: itisopen/github-actions-workflows/.github/workflows/ci-terraform.yml@itisopen
    with:
      filter-mode: nofilter
      suggestions: false
      runs-on: ${{ inputs.runs-on }}

  ci-readme:
    uses: itisopen/github-actions-workflows/.github/workflows/ci-readme.yml@itisopen
    with:
      runs-on: ${{ inputs.runs-on }}
    secrets: inherit
    
  ci-codeowners:
    uses: itisopen/github-actions-workflows/.github/workflows/ci-codeowners.yml@itisopen
    with:
      is_fork: false
      runs-on: ${{ inputs.runs-on }}
    secrets:
      github_access_token: ${{ secrets.REPO_ACCESS_TOKEN }}

  auto-release:
    needs: [ci-terraform, ci-readme, ci-codeowners]
    uses: itisopen/.github/.github/workflows/shared-auto-release.yml@itisopen
    with:
      runs-on: ${{ inputs.runs-on }}    
      publish: true
    secrets: inherit
