name: |-
  Scheduled Workflows of a Terraform Module
  
  ### Usage 
  
  In your repo create  __`.github/workflows/scheduled.yml`__
  
  ```yaml
    name: scheduled
    on:
      schedule:
        - cron: "0 3 * * *"
  
    permissions:
      pull-requests: write
      id-token: write
      contents: write
    
    jobs:
      scheduled:
        uses: itisopen/github-actions-workflows-terraform-module/.github/workflows/scheduled.yml@itisopen
        secrets:
          REPO_ACCESS_TOKEN: $\{\{ secrets.REPO_ACCESS_TOKEN \}\}
  ```

on:
  workflow_call:
    inputs:
      runs-on:
        description: "Overrides job runs-on setting (json-encoded list)"
        type: string
        required: false
        default: '["ubuntu-latest"]'
    secrets:
      REPO_ACCESS_TOKEN:
        description: "GitHub API token"
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  context:
    uses: itisopen/github-actions-workflows/.github/workflows/scheduled-context.yml@itisopen
    with:
      runs-on: ${{ inputs.runs-on }}
    secrets:
      github_access_token: ${{ secrets.REPO_ACCESS_TOKEN }}

  readme:
    uses: itisopen/github-actions-workflows/.github/workflows/scheduled-readme.yml@itisopen
    with:
      runs-on: ${{ inputs.runs-on }}
    secrets: inherit
